### ISSUE TITLE
Invalid port returned for TURN-DTLS listener?

### ISSUE THREAD

**Issue by ignatiusreza** [l7mp/stunner-auth-service#3]
Somehow the detected tls-listener configuration mapped `turn://0.0.0.0:443<32768-65535>` (shouldn't this be `turns://`?) to `public=<filtered>:3478` instead of `public=<filtered>:443` as is defined by the `Service`..

![image](https://github.com/l7mp/stunner-auth-service/assets/667726/cb3cabed-b217-4535-aeed-c3413dcafe11)

Stunner Auth Log (Formatted):

```
INFO	handler	GetIceAuth: serving ICE config request	{"params": {"service":"turn"}}
DEBUG	handler	getIceServerConf: serving ICE config request	{"params": {"service":"turn"}}
DEBUG	handler	getIceServerConfForStunnerConf: considering Stunner config	{
  "stunner-config": "{
    version=\"v1alpha1\",
    admin:{
      name=\"stunner/stunner-gateway\",
      logLevel=\"all:INFO\",
      health-check=\"http://0.0.0.0:8086\"},
      auth:{
        realm=\"stunner.l7mp.io\",
        type=\"plaintext\",
        username=\"<SECRET>\",
        password=\"<SECRET>\"},
        listeners=[
          \"stunner/stunner-gateway/udp-listener\":{
            turn://0.0.0.0:3478<32768-65535>,
            public=<filtered>:3478,
            cert/key=-/-,
            routes=[]
          },
          \"stunner/stunner-gateway/tls-listener\":{
            turn://0.0.0.0:443<32768-65535>,
            public=<filtered>:3478,
            cert/key=<SECRET>/<SECRET>,
            routes=[]
          }
        ],
      clusters=[]
    }",
  "params": {"service":"turn"}
}
DEBUG	handler	considering Listener	{"namespace": "stunner", "gateway": "stunner-gateway", "listener": "udp-listener"}
DEBUG	handler	considering Listener	{"namespace": "stunner", "gateway": "stunner-gateway", "listener": "tls-listener"}
DEBUG	handler	getIceServerConfForStunnerConf: ready	{
  "repsonse": {
    "credential":"guest","urls":["turn:<filtered>:3478?transport=udp","turns:<filtered>:3478?transport=udp"],"username":"guest"
  }
}
DEBUG	handler	getIceServerConf: ready	{
  "repsonse": {
    "iceServers":[{"credential":"guest","urls":["turn:<filtered>:3478?transport=udp","turns:<filtered>:3478?transport=udp"],"username":"guest"}],"iceTransportPolicy":"all"
  }
}
INFO	handler	GetIceAuth: ready	{
  "response": {
    "iceServers":[{"credential":"guest","urls":["turn:<filtered>:3478?transport=udp","turns:<filtered>:3478?transport=udp"],"username":"guest"}],"iceTransportPolicy":"all"
  },
  "status": 200
}
```

Sample request/response:

```
# curl http://stunner-auth:8088/ice?service=turn
{"iceServers":[{"credential":"<filtered>","urls":["turn:<filtered>:3478?transport=udp","turns:<filtered>:3478?transport=udp"],"username":"<filtered>"}],"iceTransportPolicy":"all"}
```

Gateway definition:

```yml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: stunner-gateway
spec:
  gatewayClassName: stunner-gatewayclass
  listeners:
    - name: udp-listener
      port: 3478
      protocol: TURN-UDP
    - name: tls-listener
      port: 443
      protocol: TURN-DTLS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            namespace: stunner
            name: common-tls-secret
```

**Comment by rg0now** [comment]
Thanks for the report. I could reproduce this.

**Comment by ignatiusreza** [comment]
Thank you!

Something related that I just noticed.. the `Service` for the gateway is created with the following `spec.ports`:

```yml
spec:
  ports:
    - name: udp-listener
      protocol: UDP
      port: 3478
      targetPort: 3478
      nodePort: 30910
    - name: dtls-listener
      protocol: UDP
      port: 443
      targetPort: 443
      nodePort: 32380
```

which means that the publicly accessible urls are actually `turn:<host/ip>:30910` and `turns:<host/ip>:32380`..

is there a way to configure the nodePort that is being assigned? ideally, I would like to configure it to use UDP on port 80 and DTLS on port 443, so that we don't need to configure additional firewall rules to open those additional port..

**Comment by rg0now** [comment]
> is there a way to configure the nodePort that is being assigned? ideally, I would like to configure it to use UDP on port 80 and DTLS on port 443, so that we don't need to configure additional firewall rules to open those additional port..

This only matters if you absolutely want to use nodeports (I'd recommend against this). If yes, then nodeport ranges typically must be in the range 30000-32768 and most cloud providers will not allow you to reconfigure this. This means you cannot choose arbitrary ports. So if nodeports is an absolute must, I'd recommend you open the entire nodeport range on the firewall: there is no way in the Gateway API to specify nodeports, these are always supposed to be dynamic. But it's better to just install a proper load-balancer controller

**Comment by ignatiusreza** [comment]
> https://github.com/l7mp/stunner/issues/32

Thanks for the direction! Found another clue also from this ticket.. the `GatewayConfig` need to have the following annotations for the load balancer to work as expected..

```yml
  loadBalancerServiceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
```
